// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqAaJmicB8FIGBxd2nmppA72kzJJfBZaI',
    appId: '1:1065371035020:web:574f3caec70b8eae5ee2a9',
    messagingSenderId: '1065371035020',
    projectId: 'qacc-authentication',
    authDomain: 'qacc-authentication.firebaseapp.com',
    storageBucket: 'qacc-authentication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdd0Aly1QTxMUdmoEl9y20vdfJYaa9fO0',
    appId: '1:1065371035020:android:ba5237bd09cfea7f5ee2a9',
    messagingSenderId: '1065371035020',
    projectId: 'qacc-authentication',
    storageBucket: 'qacc-authentication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2kxyUbFffn37Ty9-MYdNQ2OXhdfxXKE',
    appId: '1:1065371035020:ios:7886f3dda433c9d15ee2a9',
    messagingSenderId: '1065371035020',
    projectId: 'qacc-authentication',
    storageBucket: 'qacc-authentication.firebasestorage.app',
    androidClientId: '1065371035020-c7gssjbsnv80imicqkag3lba7hs7p3op.apps.googleusercontent.com',
    iosClientId: '1065371035020-lktp0q4iq4ggvks92m8uhmegp53mb7sq.apps.googleusercontent.com',
    iosBundleId: 'com.qacc.qaccApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb2kxyUbFffn37Ty9-MYdNQ2OXhdfxXKE',
    appId: '1:1065371035020:ios:373f1a482f3801d95ee2a9',
    messagingSenderId: '1065371035020',
    projectId: 'qacc-authentication',
    storageBucket: 'qacc-authentication.firebasestorage.app',
    iosBundleId: 'com.example.qaccApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqAaJmicB8FIGBxd2nmppA72kzJJfBZaI',
    appId: '1:1065371035020:web:608da3b807e7fd225ee2a9',
    messagingSenderId: '1065371035020',
    projectId: 'qacc-authentication',
    authDomain: 'qacc-authentication.firebaseapp.com',
    storageBucket: 'qacc-authentication.firebasestorage.app',
  );
}